# Generated by Django 4.0.5 on 2022-06-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'Ошибка', 'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
